export const posts = [
  {
    poserName: "Tampipi, Neo",
    postTime: 5,
    postContent: "Hello World!",
    reactions: 36,
    comments: 6,
    shares: 8,
  },
  {
    poserName: "Niño Mharlito Tampipi",
    postTime: 2,
    postContent: "Wazzup",
    reactions: 86,
    comments: 12,
    shares: 1,
  },
  {
    poserName: "Neo",
    postTime: 12,
    postContent: "React JS is life!",
    reactions: 999,
    comments: 999,
    shares: 999,
  },
  {
    poserName: "Mharlito",
    postTime: 8,
    postContent: "Watataps",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Baning",
    postTime: 8,
    postContent:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum?",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Tampipi, Neo",
    postTime: 5,
    postContent: "Hello World!",
    reactions: 36,
    comments: 6,
    shares: 8,
  },
  {
    poserName: "Niño Mharlito Tampipi",
    postTime: 2,
    postContent: "Wazzup",
    reactions: 86,
    comments: 12,
    shares: 1,
  },
  {
    poserName: "Neo",
    postTime: 12,
    postContent: "React JS is life!",
    reactions: 999,
    comments: 999,
    shares: 999,
  },
  {
    poserName: "Mharlito",
    postTime: 8,
    postContent: "Watataps",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Baning",
    postTime: 8,
    postContent:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum?",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Tampipi, Neo",
    postTime: 5,
    postContent: "Hello World!",
    reactions: 36,
    comments: 6,
    shares: 8,
  },
  {
    poserName: "Niño Mharlito Tampipi",
    postTime: 2,
    postContent: "Wazzup",
    reactions: 86,
    comments: 12,
    shares: 1,
  },
  {
    poserName: "Neo",
    postTime: 12,
    postContent: "React JS is life!",
    reactions: 999,
    comments: 999,
    shares: 999,
  },
  {
    poserName: "Mharlito",
    postTime: 8,
    postContent: "Watataps",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Baning",
    postTime: 8,
    postContent:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum?",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Tampipi, Neo",
    postTime: 5,
    postContent: "Hello World!",
    reactions: 36,
    comments: 6,
    shares: 8,
  },
  {
    poserName: "Niño Mharlito Tampipi",
    postTime: 2,
    postContent: "Wazzup",
    reactions: 86,
    comments: 12,
    shares: 1,
  },
  {
    poserName: "Neo",
    postTime: 12,
    postContent: "React JS is life!",
    reactions: 999,
    comments: 999,
    shares: 999,
  },
  {
    poserName: "Mharlito",
    postTime: 8,
    postContent: "Watataps",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Baning",
    postTime: 8,
    postContent:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum?",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Tampipi, Neo",
    postTime: 5,
    postContent: "Hello World!",
    reactions: 36,
    comments: 6,
    shares: 8,
  },
  {
    poserName: "Niño Mharlito Tampipi",
    postTime: 2,
    postContent: "Wazzup",
    reactions: 86,
    comments: 12,
    shares: 1,
  },
  {
    poserName: "Neo",
    postTime: 12,
    postContent: "React JS is life!",
    reactions: 999,
    comments: 999,
    shares: 999,
  },
  {
    poserName: "Mharlito",
    postTime: 8,
    postContent: "Watataps",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Baning",
    postTime: 8,
    postContent:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum?",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Tampipi, Neo",
    postTime: 5,
    postContent: "Hello World!",
    reactions: 36,
    comments: 6,
    shares: 8,
  },
  {
    poserName: "Niño Mharlito Tampipi",
    postTime: 2,
    postContent: "Wazzup",
    reactions: 86,
    comments: 12,
    shares: 1,
  },
  {
    poserName: "Neo",
    postTime: 12,
    postContent: "React JS is life!",
    reactions: 999,
    comments: 999,
    shares: 999,
  },
  {
    poserName: "Mharlito",
    postTime: 8,
    postContent: "Watataps",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
  {
    poserName: "Baning",
    postTime: 8,
    postContent:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit magnam quam sapiente commodi asperiores sequi, eaque, dolorum explicabo quas quo consectetur ex laborum esse, nisi obcaecati minima natus rerum! Dolorum?",
    reactions: 2,
    comments: 1,
    shares: 0,
  },
];
